/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package radar;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AirportOutput extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 308389631422698127L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AirportOutput\",\"namespace\":\"radar\",\"fields\":[{\"name\":\"to\",\"type\":\"string\"},{\"name\":\"from\",\"type\":\"string\"},{\"name\":\"departureTimestamp\",\"type\":\"long\"},{\"name\":\"arrivalTimestamp\",\"type\":\"long\"},{\"name\":\"duration\",\"type\":\"long\"},{\"name\":\"departureDatetime\",\"type\":\"string\"},{\"name\":\"arrivalDatetime\",\"type\":\"string\"},{\"name\":\"departureAirportCode\",\"type\":\"string\"},{\"name\":\"arrivalAirportCode\",\"type\":\"string\"},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"gate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"airline\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"date\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AirportOutput> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AirportOutput> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AirportOutput> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AirportOutput> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AirportOutput> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AirportOutput to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AirportOutput from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AirportOutput instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AirportOutput fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence to;
  private java.lang.CharSequence from;
  private long departureTimestamp;
  private long arrivalTimestamp;
  private long duration;
  private java.lang.CharSequence departureDatetime;
  private java.lang.CharSequence arrivalDatetime;
  private java.lang.CharSequence departureAirportCode;
  private java.lang.CharSequence arrivalAirportCode;
  private java.lang.CharSequence status;
  private java.lang.CharSequence gate;
  private java.lang.CharSequence airline;
  private java.lang.CharSequence id;
  private java.lang.CharSequence date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AirportOutput() {}

  /**
   * All-args constructor.
   * @param to The new value for to
   * @param from The new value for from
   * @param departureTimestamp The new value for departureTimestamp
   * @param arrivalTimestamp The new value for arrivalTimestamp
   * @param duration The new value for duration
   * @param departureDatetime The new value for departureDatetime
   * @param arrivalDatetime The new value for arrivalDatetime
   * @param departureAirportCode The new value for departureAirportCode
   * @param arrivalAirportCode The new value for arrivalAirportCode
   * @param status The new value for status
   * @param gate The new value for gate
   * @param airline The new value for airline
   * @param id The new value for id
   * @param date The new value for date
   */
  public AirportOutput(java.lang.CharSequence to, java.lang.CharSequence from, java.lang.Long departureTimestamp, java.lang.Long arrivalTimestamp, java.lang.Long duration, java.lang.CharSequence departureDatetime, java.lang.CharSequence arrivalDatetime, java.lang.CharSequence departureAirportCode, java.lang.CharSequence arrivalAirportCode, java.lang.CharSequence status, java.lang.CharSequence gate, java.lang.CharSequence airline, java.lang.CharSequence id, java.lang.CharSequence date) {
    this.to = to;
    this.from = from;
    this.departureTimestamp = departureTimestamp;
    this.arrivalTimestamp = arrivalTimestamp;
    this.duration = duration;
    this.departureDatetime = departureDatetime;
    this.arrivalDatetime = arrivalDatetime;
    this.departureAirportCode = departureAirportCode;
    this.arrivalAirportCode = arrivalAirportCode;
    this.status = status;
    this.gate = gate;
    this.airline = airline;
    this.id = id;
    this.date = date;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return to;
    case 1: return from;
    case 2: return departureTimestamp;
    case 3: return arrivalTimestamp;
    case 4: return duration;
    case 5: return departureDatetime;
    case 6: return arrivalDatetime;
    case 7: return departureAirportCode;
    case 8: return arrivalAirportCode;
    case 9: return status;
    case 10: return gate;
    case 11: return airline;
    case 12: return id;
    case 13: return date;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: to = (java.lang.CharSequence)value$; break;
    case 1: from = (java.lang.CharSequence)value$; break;
    case 2: departureTimestamp = (java.lang.Long)value$; break;
    case 3: arrivalTimestamp = (java.lang.Long)value$; break;
    case 4: duration = (java.lang.Long)value$; break;
    case 5: departureDatetime = (java.lang.CharSequence)value$; break;
    case 6: arrivalDatetime = (java.lang.CharSequence)value$; break;
    case 7: departureAirportCode = (java.lang.CharSequence)value$; break;
    case 8: arrivalAirportCode = (java.lang.CharSequence)value$; break;
    case 9: status = (java.lang.CharSequence)value$; break;
    case 10: gate = (java.lang.CharSequence)value$; break;
    case 11: airline = (java.lang.CharSequence)value$; break;
    case 12: id = (java.lang.CharSequence)value$; break;
    case 13: date = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'to' field.
   * @return The value of the 'to' field.
   */
  public java.lang.CharSequence getTo() {
    return to;
  }


  /**
   * Sets the value of the 'to' field.
   * @param value the value to set.
   */
  public void setTo(java.lang.CharSequence value) {
    this.to = value;
  }

  /**
   * Gets the value of the 'from' field.
   * @return The value of the 'from' field.
   */
  public java.lang.CharSequence getFrom() {
    return from;
  }


  /**
   * Sets the value of the 'from' field.
   * @param value the value to set.
   */
  public void setFrom(java.lang.CharSequence value) {
    this.from = value;
  }

  /**
   * Gets the value of the 'departureTimestamp' field.
   * @return The value of the 'departureTimestamp' field.
   */
  public long getDepartureTimestamp() {
    return departureTimestamp;
  }


  /**
   * Sets the value of the 'departureTimestamp' field.
   * @param value the value to set.
   */
  public void setDepartureTimestamp(long value) {
    this.departureTimestamp = value;
  }

  /**
   * Gets the value of the 'arrivalTimestamp' field.
   * @return The value of the 'arrivalTimestamp' field.
   */
  public long getArrivalTimestamp() {
    return arrivalTimestamp;
  }


  /**
   * Sets the value of the 'arrivalTimestamp' field.
   * @param value the value to set.
   */
  public void setArrivalTimestamp(long value) {
    this.arrivalTimestamp = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return The value of the 'duration' field.
   */
  public long getDuration() {
    return duration;
  }


  /**
   * Sets the value of the 'duration' field.
   * @param value the value to set.
   */
  public void setDuration(long value) {
    this.duration = value;
  }

  /**
   * Gets the value of the 'departureDatetime' field.
   * @return The value of the 'departureDatetime' field.
   */
  public java.lang.CharSequence getDepartureDatetime() {
    return departureDatetime;
  }


  /**
   * Sets the value of the 'departureDatetime' field.
   * @param value the value to set.
   */
  public void setDepartureDatetime(java.lang.CharSequence value) {
    this.departureDatetime = value;
  }

  /**
   * Gets the value of the 'arrivalDatetime' field.
   * @return The value of the 'arrivalDatetime' field.
   */
  public java.lang.CharSequence getArrivalDatetime() {
    return arrivalDatetime;
  }


  /**
   * Sets the value of the 'arrivalDatetime' field.
   * @param value the value to set.
   */
  public void setArrivalDatetime(java.lang.CharSequence value) {
    this.arrivalDatetime = value;
  }

  /**
   * Gets the value of the 'departureAirportCode' field.
   * @return The value of the 'departureAirportCode' field.
   */
  public java.lang.CharSequence getDepartureAirportCode() {
    return departureAirportCode;
  }


  /**
   * Sets the value of the 'departureAirportCode' field.
   * @param value the value to set.
   */
  public void setDepartureAirportCode(java.lang.CharSequence value) {
    this.departureAirportCode = value;
  }

  /**
   * Gets the value of the 'arrivalAirportCode' field.
   * @return The value of the 'arrivalAirportCode' field.
   */
  public java.lang.CharSequence getArrivalAirportCode() {
    return arrivalAirportCode;
  }


  /**
   * Sets the value of the 'arrivalAirportCode' field.
   * @param value the value to set.
   */
  public void setArrivalAirportCode(java.lang.CharSequence value) {
    this.arrivalAirportCode = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'gate' field.
   * @return The value of the 'gate' field.
   */
  public java.lang.CharSequence getGate() {
    return gate;
  }


  /**
   * Sets the value of the 'gate' field.
   * @param value the value to set.
   */
  public void setGate(java.lang.CharSequence value) {
    this.gate = value;
  }

  /**
   * Gets the value of the 'airline' field.
   * @return The value of the 'airline' field.
   */
  public java.lang.CharSequence getAirline() {
    return airline;
  }


  /**
   * Sets the value of the 'airline' field.
   * @param value the value to set.
   */
  public void setAirline(java.lang.CharSequence value) {
    this.airline = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.CharSequence getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.date = value;
  }

  /**
   * Creates a new AirportOutput RecordBuilder.
   * @return A new AirportOutput RecordBuilder
   */
  public static radar.AirportOutput.Builder newBuilder() {
    return new radar.AirportOutput.Builder();
  }

  /**
   * Creates a new AirportOutput RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AirportOutput RecordBuilder
   */
  public static radar.AirportOutput.Builder newBuilder(radar.AirportOutput.Builder other) {
    if (other == null) {
      return new radar.AirportOutput.Builder();
    } else {
      return new radar.AirportOutput.Builder(other);
    }
  }

  /**
   * Creates a new AirportOutput RecordBuilder by copying an existing AirportOutput instance.
   * @param other The existing instance to copy.
   * @return A new AirportOutput RecordBuilder
   */
  public static radar.AirportOutput.Builder newBuilder(radar.AirportOutput other) {
    if (other == null) {
      return new radar.AirportOutput.Builder();
    } else {
      return new radar.AirportOutput.Builder(other);
    }
  }

  /**
   * RecordBuilder for AirportOutput instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AirportOutput>
    implements org.apache.avro.data.RecordBuilder<AirportOutput> {

    private java.lang.CharSequence to;
    private java.lang.CharSequence from;
    private long departureTimestamp;
    private long arrivalTimestamp;
    private long duration;
    private java.lang.CharSequence departureDatetime;
    private java.lang.CharSequence arrivalDatetime;
    private java.lang.CharSequence departureAirportCode;
    private java.lang.CharSequence arrivalAirportCode;
    private java.lang.CharSequence status;
    private java.lang.CharSequence gate;
    private java.lang.CharSequence airline;
    private java.lang.CharSequence id;
    private java.lang.CharSequence date;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(radar.AirportOutput.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.to)) {
        this.to = data().deepCopy(fields()[0].schema(), other.to);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.from)) {
        this.from = data().deepCopy(fields()[1].schema(), other.from);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.departureTimestamp)) {
        this.departureTimestamp = data().deepCopy(fields()[2].schema(), other.departureTimestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.arrivalTimestamp)) {
        this.arrivalTimestamp = data().deepCopy(fields()[3].schema(), other.arrivalTimestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.departureDatetime)) {
        this.departureDatetime = data().deepCopy(fields()[5].schema(), other.departureDatetime);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.arrivalDatetime)) {
        this.arrivalDatetime = data().deepCopy(fields()[6].schema(), other.arrivalDatetime);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.departureAirportCode)) {
        this.departureAirportCode = data().deepCopy(fields()[7].schema(), other.departureAirportCode);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.arrivalAirportCode)) {
        this.arrivalAirportCode = data().deepCopy(fields()[8].schema(), other.arrivalAirportCode);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.status)) {
        this.status = data().deepCopy(fields()[9].schema(), other.status);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.gate)) {
        this.gate = data().deepCopy(fields()[10].schema(), other.gate);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.airline)) {
        this.airline = data().deepCopy(fields()[11].schema(), other.airline);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.id)) {
        this.id = data().deepCopy(fields()[12].schema(), other.id);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.date)) {
        this.date = data().deepCopy(fields()[13].schema(), other.date);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing AirportOutput instance
     * @param other The existing instance to copy.
     */
    private Builder(radar.AirportOutput other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.to)) {
        this.to = data().deepCopy(fields()[0].schema(), other.to);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.from)) {
        this.from = data().deepCopy(fields()[1].schema(), other.from);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.departureTimestamp)) {
        this.departureTimestamp = data().deepCopy(fields()[2].schema(), other.departureTimestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.arrivalTimestamp)) {
        this.arrivalTimestamp = data().deepCopy(fields()[3].schema(), other.arrivalTimestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.departureDatetime)) {
        this.departureDatetime = data().deepCopy(fields()[5].schema(), other.departureDatetime);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.arrivalDatetime)) {
        this.arrivalDatetime = data().deepCopy(fields()[6].schema(), other.arrivalDatetime);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.departureAirportCode)) {
        this.departureAirportCode = data().deepCopy(fields()[7].schema(), other.departureAirportCode);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.arrivalAirportCode)) {
        this.arrivalAirportCode = data().deepCopy(fields()[8].schema(), other.arrivalAirportCode);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.status)) {
        this.status = data().deepCopy(fields()[9].schema(), other.status);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.gate)) {
        this.gate = data().deepCopy(fields()[10].schema(), other.gate);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.airline)) {
        this.airline = data().deepCopy(fields()[11].schema(), other.airline);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.id)) {
        this.id = data().deepCopy(fields()[12].schema(), other.id);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.date)) {
        this.date = data().deepCopy(fields()[13].schema(), other.date);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'to' field.
      * @return The value.
      */
    public java.lang.CharSequence getTo() {
      return to;
    }


    /**
      * Sets the value of the 'to' field.
      * @param value The value of 'to'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setTo(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.to = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'to' field has been set.
      * @return True if the 'to' field has been set, false otherwise.
      */
    public boolean hasTo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'to' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearTo() {
      to = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'from' field.
      * @return The value.
      */
    public java.lang.CharSequence getFrom() {
      return from;
    }


    /**
      * Sets the value of the 'from' field.
      * @param value The value of 'from'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setFrom(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.from = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'from' field has been set.
      * @return True if the 'from' field has been set, false otherwise.
      */
    public boolean hasFrom() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'from' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearFrom() {
      from = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'departureTimestamp' field.
      * @return The value.
      */
    public long getDepartureTimestamp() {
      return departureTimestamp;
    }


    /**
      * Sets the value of the 'departureTimestamp' field.
      * @param value The value of 'departureTimestamp'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setDepartureTimestamp(long value) {
      validate(fields()[2], value);
      this.departureTimestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'departureTimestamp' field has been set.
      * @return True if the 'departureTimestamp' field has been set, false otherwise.
      */
    public boolean hasDepartureTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'departureTimestamp' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearDepartureTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'arrivalTimestamp' field.
      * @return The value.
      */
    public long getArrivalTimestamp() {
      return arrivalTimestamp;
    }


    /**
      * Sets the value of the 'arrivalTimestamp' field.
      * @param value The value of 'arrivalTimestamp'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setArrivalTimestamp(long value) {
      validate(fields()[3], value);
      this.arrivalTimestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'arrivalTimestamp' field has been set.
      * @return True if the 'arrivalTimestamp' field has been set, false otherwise.
      */
    public boolean hasArrivalTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'arrivalTimestamp' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearArrivalTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * @return The value.
      */
    public long getDuration() {
      return duration;
    }


    /**
      * Sets the value of the 'duration' field.
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setDuration(long value) {
      validate(fields()[4], value);
      this.duration = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'duration' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearDuration() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'departureDatetime' field.
      * @return The value.
      */
    public java.lang.CharSequence getDepartureDatetime() {
      return departureDatetime;
    }


    /**
      * Sets the value of the 'departureDatetime' field.
      * @param value The value of 'departureDatetime'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setDepartureDatetime(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.departureDatetime = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'departureDatetime' field has been set.
      * @return True if the 'departureDatetime' field has been set, false otherwise.
      */
    public boolean hasDepartureDatetime() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'departureDatetime' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearDepartureDatetime() {
      departureDatetime = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'arrivalDatetime' field.
      * @return The value.
      */
    public java.lang.CharSequence getArrivalDatetime() {
      return arrivalDatetime;
    }


    /**
      * Sets the value of the 'arrivalDatetime' field.
      * @param value The value of 'arrivalDatetime'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setArrivalDatetime(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.arrivalDatetime = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'arrivalDatetime' field has been set.
      * @return True if the 'arrivalDatetime' field has been set, false otherwise.
      */
    public boolean hasArrivalDatetime() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'arrivalDatetime' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearArrivalDatetime() {
      arrivalDatetime = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'departureAirportCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getDepartureAirportCode() {
      return departureAirportCode;
    }


    /**
      * Sets the value of the 'departureAirportCode' field.
      * @param value The value of 'departureAirportCode'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setDepartureAirportCode(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.departureAirportCode = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'departureAirportCode' field has been set.
      * @return True if the 'departureAirportCode' field has been set, false otherwise.
      */
    public boolean hasDepartureAirportCode() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'departureAirportCode' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearDepartureAirportCode() {
      departureAirportCode = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'arrivalAirportCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getArrivalAirportCode() {
      return arrivalAirportCode;
    }


    /**
      * Sets the value of the 'arrivalAirportCode' field.
      * @param value The value of 'arrivalAirportCode'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setArrivalAirportCode(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.arrivalAirportCode = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'arrivalAirportCode' field has been set.
      * @return True if the 'arrivalAirportCode' field has been set, false otherwise.
      */
    public boolean hasArrivalAirportCode() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'arrivalAirportCode' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearArrivalAirportCode() {
      arrivalAirportCode = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.status = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearStatus() {
      status = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'gate' field.
      * @return The value.
      */
    public java.lang.CharSequence getGate() {
      return gate;
    }


    /**
      * Sets the value of the 'gate' field.
      * @param value The value of 'gate'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setGate(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.gate = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'gate' field has been set.
      * @return True if the 'gate' field has been set, false otherwise.
      */
    public boolean hasGate() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'gate' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearGate() {
      gate = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'airline' field.
      * @return The value.
      */
    public java.lang.CharSequence getAirline() {
      return airline;
    }


    /**
      * Sets the value of the 'airline' field.
      * @param value The value of 'airline'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setAirline(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.airline = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'airline' field has been set.
      * @return True if the 'airline' field has been set, false otherwise.
      */
    public boolean hasAirline() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'airline' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearAirline() {
      airline = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setId(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.id = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearId() {
      id = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.CharSequence getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public radar.AirportOutput.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.date = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public radar.AirportOutput.Builder clearDate() {
      date = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AirportOutput build() {
      try {
        AirportOutput record = new AirportOutput();
        record.to = fieldSetFlags()[0] ? this.to : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.from = fieldSetFlags()[1] ? this.from : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.departureTimestamp = fieldSetFlags()[2] ? this.departureTimestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.arrivalTimestamp = fieldSetFlags()[3] ? this.arrivalTimestamp : (java.lang.Long) defaultValue(fields()[3]);
        record.duration = fieldSetFlags()[4] ? this.duration : (java.lang.Long) defaultValue(fields()[4]);
        record.departureDatetime = fieldSetFlags()[5] ? this.departureDatetime : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.arrivalDatetime = fieldSetFlags()[6] ? this.arrivalDatetime : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.departureAirportCode = fieldSetFlags()[7] ? this.departureAirportCode : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.arrivalAirportCode = fieldSetFlags()[8] ? this.arrivalAirportCode : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.status = fieldSetFlags()[9] ? this.status : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.gate = fieldSetFlags()[10] ? this.gate : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.airline = fieldSetFlags()[11] ? this.airline : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.id = fieldSetFlags()[12] ? this.id : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.date = fieldSetFlags()[13] ? this.date : (java.lang.CharSequence) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AirportOutput>
    WRITER$ = (org.apache.avro.io.DatumWriter<AirportOutput>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AirportOutput>
    READER$ = (org.apache.avro.io.DatumReader<AirportOutput>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.to);

    out.writeString(this.from);

    out.writeLong(this.departureTimestamp);

    out.writeLong(this.arrivalTimestamp);

    out.writeLong(this.duration);

    out.writeString(this.departureDatetime);

    out.writeString(this.arrivalDatetime);

    out.writeString(this.departureAirportCode);

    out.writeString(this.arrivalAirportCode);

    if (this.status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.status);
    }

    if (this.gate == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.gate);
    }

    if (this.airline == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.airline);
    }

    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.id);
    }

    if (this.date == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.date);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.to = in.readString(this.to instanceof Utf8 ? (Utf8)this.to : null);

      this.from = in.readString(this.from instanceof Utf8 ? (Utf8)this.from : null);

      this.departureTimestamp = in.readLong();

      this.arrivalTimestamp = in.readLong();

      this.duration = in.readLong();

      this.departureDatetime = in.readString(this.departureDatetime instanceof Utf8 ? (Utf8)this.departureDatetime : null);

      this.arrivalDatetime = in.readString(this.arrivalDatetime instanceof Utf8 ? (Utf8)this.arrivalDatetime : null);

      this.departureAirportCode = in.readString(this.departureAirportCode instanceof Utf8 ? (Utf8)this.departureAirportCode : null);

      this.arrivalAirportCode = in.readString(this.arrivalAirportCode instanceof Utf8 ? (Utf8)this.arrivalAirportCode : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.status = null;
      } else {
        this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.gate = null;
      } else {
        this.gate = in.readString(this.gate instanceof Utf8 ? (Utf8)this.gate : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.airline = null;
      } else {
        this.airline = in.readString(this.airline instanceof Utf8 ? (Utf8)this.airline : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.date = null;
      } else {
        this.date = in.readString(this.date instanceof Utf8 ? (Utf8)this.date : null);
      }

    } else {
      for (int i = 0; i < 14; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.to = in.readString(this.to instanceof Utf8 ? (Utf8)this.to : null);
          break;

        case 1:
          this.from = in.readString(this.from instanceof Utf8 ? (Utf8)this.from : null);
          break;

        case 2:
          this.departureTimestamp = in.readLong();
          break;

        case 3:
          this.arrivalTimestamp = in.readLong();
          break;

        case 4:
          this.duration = in.readLong();
          break;

        case 5:
          this.departureDatetime = in.readString(this.departureDatetime instanceof Utf8 ? (Utf8)this.departureDatetime : null);
          break;

        case 6:
          this.arrivalDatetime = in.readString(this.arrivalDatetime instanceof Utf8 ? (Utf8)this.arrivalDatetime : null);
          break;

        case 7:
          this.departureAirportCode = in.readString(this.departureAirportCode instanceof Utf8 ? (Utf8)this.departureAirportCode : null);
          break;

        case 8:
          this.arrivalAirportCode = in.readString(this.arrivalAirportCode instanceof Utf8 ? (Utf8)this.arrivalAirportCode : null);
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status = null;
          } else {
            this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.gate = null;
          } else {
            this.gate = in.readString(this.gate instanceof Utf8 ? (Utf8)this.gate : null);
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.airline = null;
          } else {
            this.airline = in.readString(this.airline instanceof Utf8 ? (Utf8)this.airline : null);
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.date = null;
          } else {
            this.date = in.readString(this.date instanceof Utf8 ? (Utf8)this.date : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










